services:
  mysql-server:
    platform: linux/x86_64
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "mlwarehouse"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    healthcheck:
      test: mysqladmin ping
      interval: 10s
      timeout: 5s
      retries: 10

  irods-server:
    container_name: irods-server
    image: "ghcr.io/wtsi-npg/ub-18.04-irods-${IRODS_VERSION:-4.2.11}:${DOCKER_TAG:-latest}"
    restart: always
    ports:
      - "1247:1247"
      - "20000-20199:20000-20199"

  irods-clients:
    container_name: irods-clients
    image: "ghcr.io/wtsi-npg/ub-18.04-irods-clients-${IRODS_VERSION:-4.2.11}:${DOCKER_TAG:-latest}"
    volumes:
      - "${PWD}:${PWD}"
      - "${PWD}/tests/.irods:${HOME}/.irods/"
    environment:
      CLIENT_USER: "${USER:? \nERROR: The USER environment variable is unset}"
      CLIENT_USER_ID: "${UID:? \nERROR: The UID environment variable is unset}"
      CLIENT_USER_HOME: "${HOME}"
      IRODS_ENVIRONMENT_FILE: "${HOME}/.irods/irods_environment.json"
    command: sleep infinity
    depends_on:
      - irods-server
