[tool.poetry]
name = "npg-irods-python"
version = "0.1.0"
description = "Applications for the management of data and metadata in iRODS."
authors = ["Keith James <kdj@sanger.ac.uk>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/wtsi-npg/npg-irods-python"

[tool.poetry.dependencies]
python = "^3.10"
black = "^22.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
